
server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/board?autoReconnect=true
        username: dogyun
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
